server:
  port: 8067
  servlet:
    context-path: /api/awesome-pizza
spring:
  application:
    name: pizza
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/awesome-pizza-db
    username: awesome-pizza-db
    password: awesome-pizza-db-pw
  flyway:
    enabled: true
    locations: classpath:/db/migration/postgresql
    baseline-on-migrate: true
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    root: INFO

