
name: Build image for pizza-be

on:
  push:
    branches: [  "main" ]
    paths:
      - "pizza-be/**"
      - ".github/workflows/pizza-be-action.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pintucco/awesome-pizza/pizza-be
  VERSION: ${{github.sha}}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven tests
        run: |
          cd pizza-be
          chmod +x mvnw
          ./mvnw test
  package:
    name: Build docker image and push to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Docker Image with Maven
        run: |
          cd pizza-be
          chmod +x mvnw
          ./mvnw spring-boot:build-image \
          -DskipTests=true
      - name: Log into GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Push flagged latest image to ghcr
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\
                     ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}